/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnalyticsSummary {
  'totalBookings' : bigint,
  'totalPackages' : bigint,
  'totalLeads' : bigint,
  'conversionRate' : bigint,
  'totalRevenue' : bigint,
  'totalCustomers' : bigint,
}
export interface Booking {
  'id' : bigint,
  'status' : string,
  'checkIn' : string,
  'createdAt' : Time,
  'notes' : string,
  'bookingType' : string,
  'checkOut' : string,
  'amount' : bigint,
  'bookingRef' : string,
  'vendorName' : string,
  'packageId' : bigint,
}
export interface CompanySettings {
  'twitter' : string,
  'tagline' : string,
  'gstNumber' : string,
  'instagram' : string,
  'logo' : string,
  'whatsapp' : string,
  'email' : string,
  'website' : string,
  'facebook' : string,
  'address' : string,
  'companyName' : string,
  'phone' : string,
}
export interface CredentialAccount {
  'id' : bigint,
  'username' : string,
  'displayName' : string,
  'createdAt' : Time,
  'role' : string,
  'isActive' : boolean,
  'passwordHash' : string,
}
export interface DestinationCount { 'destination' : string, 'count' : bigint }
export interface GuestDetails {
  'name' : string,
  'travelDates' : string,
  'whatsapp' : string,
  'email' : string,
  'children' : bigint,
  'notes' : string,
  'adults' : bigint,
  'contactNumber' : string,
}
export interface HotelRate {
  'hotelName' : string,
  'rate' : bigint,
  'roomType' : string,
}
export interface InteractionLog {
  'interactionType' : string,
  'date' : Time,
  'createdBy' : Principal,
  'notes' : string,
  'channel' : string,
}
export interface Invoice {
  'id' : bigint,
  'status' : string,
  'lineItems' : Array<InvoiceLineItem>,
  'taxPercent' : bigint,
  'dueDate' : Time,
  'guestName' : string,
  'issuedDate' : Time,
  'grandTotal' : bigint,
  'invoiceNumber' : string,
  'notes' : string,
  'taxAmount' : bigint,
  'packageId' : bigint,
  'subtotal' : bigint,
}
export interface InvoiceLineItem {
  'qty' : bigint,
  'total' : bigint,
  'description' : string,
  'unitPrice' : bigint,
}
export interface ItineraryDay {
  'id' : bigint,
  'meals' : string,
  'title' : string,
  'hotel' : string,
  'date' : string,
  'activities' : Array<string>,
  'description' : string,
  'dayNumber' : bigint,
  'notes' : string,
  'packageId' : bigint,
}
export interface Lead {
  'id' : bigint,
  'destination' : string,
  'assignedTo' : string,
  'source' : string,
  'createdAt' : Time,
  'travelDates' : string,
  'guestName' : string,
  'email' : string,
  'lastModified' : Time,
  'stage' : string,
  'notes' : string,
  'linkedPackageId' : bigint,
  'phone' : string,
  'budget' : bigint,
  'followUpDate' : Time,
}
export interface LeadActivity {
  'id' : bigint,
  'action' : string,
  'date' : Time,
  'createdBy' : Principal,
  'leadId' : bigint,
  'notes' : string,
}
export interface LoginResult {
  'accountId' : bigint,
  'displayName' : string,
  'role' : string,
  'message' : string,
  'success' : boolean,
}
export interface Package {
  'id' : bigint,
  'hotel' : string,
  'templateId' : bigint,
  'createdAt' : Time,
  'createdBy' : Principal,
  'activities' : Array<string>,
  'totalCost' : bigint,
  'boating' : string,
  'lastModified' : Time,
  'foodPackage' : string,
  'guest' : GuestDetails,
  'addOns' : Array<string>,
  'category' : string,
  'travelOption' : string,
  'roomType' : string,
}
export interface PackageTemplate {
  'id' : bigint,
  'layout' : string,
  'design' : string,
  'category' : string,
  'sections' : string,
  'colorScheme' : string,
}
export interface Promotion {
  'id' : bigint,
  'categories' : Array<string>,
  'validFrom' : Time,
  'name' : string,
  'createdAt' : Time,
  'description' : string,
  'discountPercent' : bigint,
  'validTo' : Time,
  'isActive' : boolean,
}
export interface RateOption { 'name' : string, 'price' : bigint }
export interface Reminder {
  'id' : bigint,
  'status' : string,
  'createdBy' : Principal,
  'reminderDate' : Time,
  'entityId' : bigint,
  'reminderType' : string,
  'message' : string,
  'entityType' : string,
}
export interface Review {
  'id' : bigint,
  'destination' : string,
  'isPublished' : boolean,
  'createdAt' : Time,
  'guestName' : string,
  'comment' : string,
  'travelDate' : string,
  'rating' : bigint,
}
export interface StageCount { 'count' : bigint, 'stage' : string }
export type Time = bigint;
export interface UserPrivileges {
  'promotions' : boolean,
  'companySettings' : boolean,
  'dashboard' : boolean,
  'reviews' : boolean,
  'vendors' : boolean,
  'accountId' : bigint,
  'bookings' : boolean,
  'analytics' : boolean,
  'leads' : boolean,
  'rateManagement' : boolean,
  'newPackage' : boolean,
  'packagesLibrary' : boolean,
  'invoices' : boolean,
  'reminders' : boolean,
  'customers' : boolean,
}
export interface UserProfile {
  'name' : string,
  'role' : string,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Vendor {
  'id' : bigint,
  'contactName' : string,
  'name' : string,
  'createdAt' : Time,
  'email' : string,
  'notes' : string,
  'commissionRate' : bigint,
  'phone' : string,
  'vendorType' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addHotelRate' : ActorMethod<[string, string, bigint], undefined>,
  'addInteractionLog' : ActorMethod<[string, InteractionLog], undefined>,
  'addItineraryDay' : ActorMethod<
    [
      bigint,
      bigint,
      string,
      string,
      string,
      Array<string>,
      string,
      string,
      string,
    ],
    bigint
  >,
  'addLeadActivity' : ActorMethod<[bigint, string, string], undefined>,
  'addOrUpdateActivityRate' : ActorMethod<[string, bigint], undefined>,
  'addOrUpdateAddOnRate' : ActorMethod<[string, bigint], undefined>,
  'addOrUpdateBoatingRate' : ActorMethod<[string, bigint], undefined>,
  'addOrUpdateCustomer' : ActorMethod<[GuestDetails], undefined>,
  'addOrUpdateFoodRate' : ActorMethod<[string, bigint], undefined>,
  'addOrUpdateTravelRate' : ActorMethod<[string, bigint], undefined>,
  'addReview' : ActorMethod<[string, bigint, string, string, string], bigint>,
  'addTemplate' : ActorMethod<[PackageTemplate], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'calculateTotalCost' : ActorMethod<
    [
      string,
      bigint,
      bigint,
      Array<bigint>,
      bigint,
      Array<bigint>,
      bigint,
      bigint,
    ],
    bigint
  >,
  'createBooking' : ActorMethod<
    [bigint, string, string, string, string, string, bigint, string],
    bigint
  >,
  'createCredentialUser' : ActorMethod<
    [string, string, string, string],
    bigint
  >,
  'createInvoice' : ActorMethod<
    [bigint, string, Array<InvoiceLineItem>, bigint, bigint, string, Time],
    bigint
  >,
  'createLead' : ActorMethod<
    [string, string, string, string, string, bigint, string, string],
    bigint
  >,
  'createPromotion' : ActorMethod<
    [string, bigint, Time, Time, Array<string>, string],
    bigint
  >,
  'createReminder' : ActorMethod<
    [bigint, string, Time, string, string],
    bigint
  >,
  'createVendor' : ActorMethod<
    [string, string, string, string, string, bigint, string],
    bigint
  >,
  'deleteActivityRate' : ActorMethod<[string], undefined>,
  'deleteAddOnRate' : ActorMethod<[string], undefined>,
  'deleteBoatingRate' : ActorMethod<[string], undefined>,
  'deleteBooking' : ActorMethod<[bigint], undefined>,
  'deleteCredentialUser' : ActorMethod<[bigint], undefined>,
  'deleteFoodRate' : ActorMethod<[string], undefined>,
  'deleteHotelRate' : ActorMethod<[string], undefined>,
  'deleteItineraryDay' : ActorMethod<[bigint], undefined>,
  'deleteLead' : ActorMethod<[bigint], undefined>,
  'deletePackage' : ActorMethod<[bigint], undefined>,
  'deletePromotion' : ActorMethod<[bigint], undefined>,
  'deleteRateOption' : ActorMethod<[string, string], undefined>,
  'deleteReminder' : ActorMethod<[bigint], undefined>,
  'deleteReview' : ActorMethod<[bigint], undefined>,
  'deleteTemplate' : ActorMethod<[bigint], undefined>,
  'deleteTravelRate' : ActorMethod<[string], undefined>,
  'deleteVendor' : ActorMethod<[bigint], undefined>,
  'getActivePromotions' : ActorMethod<[], Array<Promotion>>,
  'getAllActivityRates' : ActorMethod<[], Array<RateOption>>,
  'getAllAddOnRates' : ActorMethod<[], Array<RateOption>>,
  'getAllBoatingRates' : ActorMethod<[], Array<RateOption>>,
  'getAllFoodRates' : ActorMethod<[], Array<RateOption>>,
  'getAllInvoices' : ActorMethod<[], Array<Invoice>>,
  'getAllPackages' : ActorMethod<[], Array<Package>>,
  'getAllTravelRates' : ActorMethod<[], Array<RateOption>>,
  'getAnalyticsSummary' : ActorMethod<[], AnalyticsSummary>,
  'getBookings' : ActorMethod<[], Array<Booking>>,
  'getBookingsByPackage' : ActorMethod<[bigint], Array<Booking>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategories' : ActorMethod<[], Array<string>>,
  'getCompanySettings' : ActorMethod<[], [] | [CompanySettings]>,
  'getGuestRecords' : ActorMethod<[], Array<GuestDetails>>,
  'getHotelRates' : ActorMethod<[], Array<HotelRate>>,
  'getInteractionLog' : ActorMethod<[string], Array<InteractionLog>>,
  'getInvoice' : ActorMethod<[bigint], [] | [Invoice]>,
  'getInvoicesByPackage' : ActorMethod<[bigint], Array<Invoice>>,
  'getItineraryByPackage' : ActorMethod<[bigint], Array<ItineraryDay>>,
  'getLeadActivities' : ActorMethod<[bigint], Array<LeadActivity>>,
  'getLeadById' : ActorMethod<[bigint], [] | [Lead]>,
  'getLeads' : ActorMethod<[], Array<Lead>>,
  'getLeadsByStage' : ActorMethod<[], Array<StageCount>>,
  'getPackages' : ActorMethod<[], Array<Package>>,
  'getPromotions' : ActorMethod<[], Array<Promotion>>,
  'getPublicPrivileges' : ActorMethod<[bigint], [] | [UserPrivileges]>,
  'getPublishedReviews' : ActorMethod<[], Array<Review>>,
  'getReminders' : ActorMethod<[], Array<Reminder>>,
  'getRemindersByEntity' : ActorMethod<[bigint, string], Array<Reminder>>,
  'getReviews' : ActorMethod<[], Array<Review>>,
  'getTemplates' : ActorMethod<[], Array<PackageTemplate>>,
  'getTemplatesByCategory' : ActorMethod<[string], Array<PackageTemplate>>,
  'getTopDestinations' : ActorMethod<[], Array<DestinationCount>>,
  'getUserPrivileges' : ActorMethod<[bigint], [] | [UserPrivileges]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVendorById' : ActorMethod<[bigint], [] | [Vendor]>,
  'getVendors' : ActorMethod<[], Array<Vendor>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listCredentialUsers' : ActorMethod<[], Array<CredentialAccount>>,
  'loginWithCredentials' : ActorMethod<[string, string], LoginResult>,
  'markInvoicePaid' : ActorMethod<[bigint], undefined>,
  'markReminderDone' : ActorMethod<[bigint], undefined>,
  'resetCredentialPassword' : ActorMethod<[bigint, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveCompanySettings' : ActorMethod<[CompanySettings], undefined>,
  'savePackage' : ActorMethod<[Package], undefined>,
  'setUserPrivileges' : ActorMethod<[UserPrivileges], undefined>,
  'updateBooking' : ActorMethod<[Booking], undefined>,
  'updateCredentialUser' : ActorMethod<
    [bigint, string, string, boolean],
    undefined
  >,
  'updateHotelRate' : ActorMethod<[string, string, bigint], undefined>,
  'updateInvoice' : ActorMethod<[Invoice], undefined>,
  'updateItineraryDay' : ActorMethod<[ItineraryDay], undefined>,
  'updateLead' : ActorMethod<[Lead], undefined>,
  'updateLeadStage' : ActorMethod<[bigint, string], undefined>,
  'updatePromotion' : ActorMethod<[Promotion], undefined>,
  'updateReminder' : ActorMethod<[Reminder], undefined>,
  'updateReview' : ActorMethod<[Review], undefined>,
  'updateTemplate' : ActorMethod<[PackageTemplate], undefined>,
  'updateVendor' : ActorMethod<[Vendor], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];