/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface InteractionLog {
    interactionType: string;
    date: Time;
    createdBy: Principal;
    notes: string;
    channel: string;
}
export interface UserProfile {
    name: string;
    role: string;
    email: string;
}
export interface AnalyticsSummary {
    totalBookings: bigint;
    totalPackages: bigint;
    totalLeads: bigint;
    conversionRate: bigint;
    totalRevenue: bigint;
    totalCustomers: bigint;
}
export type Time = bigint;
export interface RateOption {
    name: string;
    price: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Lead {
    id: bigint;
    destination: string;
    assignedTo: string;
    source: string;
    createdAt: Time;
    travelDates: string;
    guestName: string;
    email: string;
    lastModified: Time;
    stage: string;
    notes: string;
    linkedPackageId: bigint;
    phone: string;
    budget: bigint;
    followUpDate: Time;
}
export interface ItineraryDay {
    id: bigint;
    meals: string;
    title: string;
    hotel: string;
    date: string;
    activities: Array<string>;
    description: string;
    dayNumber: bigint;
    notes: string;
    packageId: bigint;
}
export interface Reminder {
    id: bigint;
    status: string;
    createdBy: Principal;
    reminderDate: Time;
    entityId: bigint;
    reminderType: string;
    message: string;
    entityType: string;
}
export interface CompanySettings {
    twitter: string;
    tagline: string;
    gstNumber: string;
    instagram: string;
    logo: string;
    whatsapp: string;
    email: string;
    website: string;
    facebook: string;
    address: string;
    companyName: string;
    phone: string;
}
export interface Booking {
    id: bigint;
    status: string;
    checkIn: string;
    createdAt: Time;
    notes: string;
    bookingType: string;
    checkOut: string;
    amount: bigint;
    bookingRef: string;
    vendorName: string;
    packageId: bigint;
}
export interface GuestDetails {
    name: string;
    travelDates: string;
    whatsapp: string;
    email: string;
    children: bigint;
    notes: string;
    adults: bigint;
    contactNumber: string;
}
export interface Vendor {
    id: bigint;
    contactName: string;
    name: string;
    createdAt: Time;
    email: string;
    notes: string;
    commissionRate: bigint;
    phone: string;
    vendorType: string;
}
export interface Review {
    id: bigint;
    destination: string;
    isPublished: boolean;
    createdAt: Time;
    guestName: string;
    comment: string;
    travelDate: string;
    rating: bigint;
}
export interface UserPrivileges {
    promotions: boolean;
    companySettings: boolean;
    dashboard: boolean;
    reviews: boolean;
    vendors: boolean;
    accountId: bigint;
    bookings: boolean;
    analytics: boolean;
    leads: boolean;
    rateManagement: boolean;
    newPackage: boolean;
    packagesLibrary: boolean;
    invoices: boolean;
    reminders: boolean;
    customers: boolean;
}
export interface Promotion {
    id: bigint;
    categories: Array<string>;
    validFrom: Time;
    name: string;
    createdAt: Time;
    description: string;
    discountPercent: bigint;
    validTo: Time;
    isActive: boolean;
}
export interface PackageTemplate {
    id: bigint;
    layout: string;
    design: string;
    category: string;
    sections: string;
    colorScheme: string;
}
export interface CredentialAccount {
    id: bigint;
    username: string;
    displayName: string;
    createdAt: Time;
    role: string;
    isActive: boolean;
    passwordHash: string;
}
export interface LeadActivity {
    id: bigint;
    action: string;
    date: Time;
    createdBy: Principal;
    leadId: bigint;
    notes: string;
}
export interface StageCount {
    count: bigint;
    stage: string;
}
export interface Package {
    id: bigint;
    hotel: string;
    templateId: bigint;
    createdAt: Time;
    createdBy: Principal;
    activities: Array<string>;
    totalCost: bigint;
    boating: string;
    lastModified: Time;
    foodPackage: string;
    guest: GuestDetails;
    addOns: Array<string>;
    category: string;
    travelOption: string;
    roomType: string;
}
export interface Invoice {
    id: bigint;
    status: string;
    lineItems: Array<InvoiceLineItem>;
    taxPercent: bigint;
    dueDate: Time;
    guestName: string;
    issuedDate: Time;
    grandTotal: bigint;
    invoiceNumber: string;
    notes: string;
    taxAmount: bigint;
    packageId: bigint;
    subtotal: bigint;
}
export interface HotelRate {
    hotelName: string;
    rate: bigint;
    roomType: string;
}
export interface DestinationCount {
    destination: string;
    count: bigint;
}
export interface LoginResult {
    accountId: bigint;
    displayName: string;
    role: string;
    message: string;
    success: boolean;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface InvoiceLineItem {
    qty: bigint;
    total: bigint;
    description: string;
    unitPrice: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addHotelRate(hotelName: string, roomType: string, rate: bigint): Promise<void>;
    addInteractionLog(customerName: string, log: InteractionLog): Promise<void>;
    addItineraryDay(packageId: bigint, dayNumber: bigint, date: string, title: string, description: string, activities: Array<string>, hotel: string, meals: string, notes: string): Promise<bigint>;
    addLeadActivity(leadId: bigint, action: string, notes: string): Promise<void>;
    addOrUpdateActivityRate(name: string, price: bigint): Promise<void>;
    addOrUpdateAddOnRate(name: string, price: bigint): Promise<void>;
    addOrUpdateBoatingRate(name: string, price: bigint): Promise<void>;
    addOrUpdateCustomer(guest: GuestDetails): Promise<void>;
    addOrUpdateFoodRate(name: string, price: bigint): Promise<void>;
    addOrUpdateTravelRate(name: string, price: bigint): Promise<void>;
    addReview(guestName: string, rating: bigint, comment: string, destination: string, travelDate: string): Promise<bigint>;
    addTemplate(template: PackageTemplate): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    calculateTotalCost(hotel: string, foodRate: bigint, travelRate: bigint, activities: Array<bigint>, boatingRate: bigint, addOnRatesList: Array<bigint>, adults: bigint, children: bigint): Promise<bigint>;
    createBooking(packageId: bigint, bookingType: string, vendorName: string, bookingRef: string, checkIn: string, checkOut: string, amount: bigint, notes: string): Promise<bigint>;
    createCredentialUser(username: string, passwordHash: string, displayName: string, role: string): Promise<bigint>;
    createInvoice(packageId: bigint, guestName: string, lineItems: Array<InvoiceLineItem>, subtotal: bigint, taxPercent: bigint, notes: string, dueDate: Time): Promise<bigint>;
    createLead(guestName: string, phone: string, email: string, destination: string, travelDates: string, budget: bigint, source: string, notes: string): Promise<bigint>;
    createPromotion(name: string, discountPercent: bigint, validFrom: Time, validTo: Time, categories: Array<string>, description: string): Promise<bigint>;
    createReminder(entityId: bigint, entityType: string, reminderDate: Time, reminderType: string, message: string): Promise<bigint>;
    createVendor(name: string, vendorType: string, contactName: string, phone: string, email: string, commissionRate: bigint, notes: string): Promise<bigint>;
    deleteActivityRate(name: string): Promise<void>;
    deleteAddOnRate(name: string): Promise<void>;
    deleteBoatingRate(name: string): Promise<void>;
    deleteBooking(bookingId: bigint): Promise<void>;
    deleteCredentialUser(id: bigint): Promise<void>;
    deleteFoodRate(name: string): Promise<void>;
    deleteHotelRate(hotelName: string): Promise<void>;
    deleteItineraryDay(dayId: bigint): Promise<void>;
    deleteLead(leadId: bigint): Promise<void>;
    deletePackage(packageId: bigint): Promise<void>;
    deletePromotion(promotionId: bigint): Promise<void>;
    deleteRateOption(category: string, name: string): Promise<void>;
    deleteReminder(reminderId: bigint): Promise<void>;
    deleteReview(reviewId: bigint): Promise<void>;
    deleteTemplate(templateId: bigint): Promise<void>;
    deleteTravelRate(name: string): Promise<void>;
    deleteVendor(vendorId: bigint): Promise<void>;
    getActivePromotions(): Promise<Array<Promotion>>;
    getAllActivityRates(): Promise<Array<RateOption>>;
    getAllAddOnRates(): Promise<Array<RateOption>>;
    getAllBoatingRates(): Promise<Array<RateOption>>;
    getAllFoodRates(): Promise<Array<RateOption>>;
    getAllInvoices(): Promise<Array<Invoice>>;
    getAllPackages(): Promise<Array<Package>>;
    getAllTravelRates(): Promise<Array<RateOption>>;
    getAnalyticsSummary(): Promise<AnalyticsSummary>;
    getBookings(): Promise<Array<Booking>>;
    getBookingsByPackage(packageId: bigint): Promise<Array<Booking>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCategories(): Promise<Array<string>>;
    getCompanySettings(): Promise<CompanySettings | null>;
    getGuestRecords(): Promise<Array<GuestDetails>>;
    getHotelRates(): Promise<Array<HotelRate>>;
    getInteractionLog(customerName: string): Promise<Array<InteractionLog>>;
    getInvoice(invoiceId: bigint): Promise<Invoice | null>;
    getInvoicesByPackage(packageId: bigint): Promise<Array<Invoice>>;
    getItineraryByPackage(packageId: bigint): Promise<Array<ItineraryDay>>;
    getLeadActivities(leadId: bigint): Promise<Array<LeadActivity>>;
    getLeadById(leadId: bigint): Promise<Lead | null>;
    getLeads(): Promise<Array<Lead>>;
    getLeadsByStage(): Promise<Array<StageCount>>;
    getPackages(): Promise<Array<Package>>;
    getPromotions(): Promise<Array<Promotion>>;
    getPublicPrivileges(accountId: bigint): Promise<UserPrivileges | null>;
    getPublishedReviews(): Promise<Array<Review>>;
    getReminders(): Promise<Array<Reminder>>;
    getRemindersByEntity(entityId: bigint, entityType: string): Promise<Array<Reminder>>;
    getReviews(): Promise<Array<Review>>;
    getTemplates(): Promise<Array<PackageTemplate>>;
    getTemplatesByCategory(category: string): Promise<Array<PackageTemplate>>;
    getTopDestinations(): Promise<Array<DestinationCount>>;
    getUserPrivileges(accountId: bigint): Promise<UserPrivileges | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVendorById(vendorId: bigint): Promise<Vendor | null>;
    getVendors(): Promise<Array<Vendor>>;
    isCallerAdmin(): Promise<boolean>;
    listCredentialUsers(): Promise<Array<CredentialAccount>>;
    loginWithCredentials(username: string, passwordHash: string): Promise<LoginResult>;
    markInvoicePaid(invoiceId: bigint): Promise<void>;
    markReminderDone(reminderId: bigint): Promise<void>;
    resetCredentialPassword(id: bigint, newPasswordHash: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveCompanySettings(settings: CompanySettings): Promise<void>;
    savePackage(pkg: Package): Promise<void>;
    setUserPrivileges(privileges: UserPrivileges): Promise<void>;
    updateBooking(booking: Booking): Promise<void>;
    updateCredentialUser(id: bigint, displayName: string, role: string, isActive: boolean): Promise<void>;
    updateHotelRate(hotelName: string, roomType: string, rate: bigint): Promise<void>;
    updateInvoice(invoice: Invoice): Promise<void>;
    updateItineraryDay(day: ItineraryDay): Promise<void>;
    updateLead(lead: Lead): Promise<void>;
    updateLeadStage(leadId: bigint, stage: string): Promise<void>;
    updatePromotion(promotion: Promotion): Promise<void>;
    updateReminder(reminder: Reminder): Promise<void>;
    updateReview(review: Review): Promise<void>;
    updateTemplate(template: PackageTemplate): Promise<void>;
    updateVendor(vendor: Vendor): Promise<void>;
}
import type { CompanySettings as _CompanySettings, Invoice as _Invoice, Lead as _Lead, UserPrivileges as _UserPrivileges, UserProfile as _UserProfile, UserRole as _UserRole, Vendor as _Vendor, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addHotelRate(arg0: string, arg1: string, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addHotelRate(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addHotelRate(arg0, arg1, arg2);
            return result;
        }
    }
    async addInteractionLog(arg0: string, arg1: InteractionLog): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addInteractionLog(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addInteractionLog(arg0, arg1);
            return result;
        }
    }
    async addItineraryDay(arg0: bigint, arg1: bigint, arg2: string, arg3: string, arg4: string, arg5: Array<string>, arg6: string, arg7: string, arg8: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addItineraryDay(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addItineraryDay(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
    async addLeadActivity(arg0: bigint, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addLeadActivity(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addLeadActivity(arg0, arg1, arg2);
            return result;
        }
    }
    async addOrUpdateActivityRate(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrUpdateActivityRate(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrUpdateActivityRate(arg0, arg1);
            return result;
        }
    }
    async addOrUpdateAddOnRate(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrUpdateAddOnRate(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrUpdateAddOnRate(arg0, arg1);
            return result;
        }
    }
    async addOrUpdateBoatingRate(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrUpdateBoatingRate(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrUpdateBoatingRate(arg0, arg1);
            return result;
        }
    }
    async addOrUpdateCustomer(arg0: GuestDetails): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrUpdateCustomer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrUpdateCustomer(arg0);
            return result;
        }
    }
    async addOrUpdateFoodRate(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrUpdateFoodRate(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrUpdateFoodRate(arg0, arg1);
            return result;
        }
    }
    async addOrUpdateTravelRate(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrUpdateTravelRate(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrUpdateTravelRate(arg0, arg1);
            return result;
        }
    }
    async addReview(arg0: string, arg1: bigint, arg2: string, arg3: string, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addReview(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReview(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async addTemplate(arg0: PackageTemplate): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTemplate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTemplate(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async calculateTotalCost(arg0: string, arg1: bigint, arg2: bigint, arg3: Array<bigint>, arg4: bigint, arg5: Array<bigint>, arg6: bigint, arg7: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.calculateTotalCost(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculateTotalCost(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async createBooking(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: bigint, arg7: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createBooking(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBooking(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async createCredentialUser(arg0: string, arg1: string, arg2: string, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createCredentialUser(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCredentialUser(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createInvoice(arg0: bigint, arg1: string, arg2: Array<InvoiceLineItem>, arg3: bigint, arg4: bigint, arg5: string, arg6: Time): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createInvoice(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createInvoice(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async createLead(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: bigint, arg6: string, arg7: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createLead(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLead(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async createPromotion(arg0: string, arg1: bigint, arg2: Time, arg3: Time, arg4: Array<string>, arg5: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createPromotion(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPromotion(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async createReminder(arg0: bigint, arg1: string, arg2: Time, arg3: string, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createReminder(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createReminder(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createVendor(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: bigint, arg6: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createVendor(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createVendor(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async deleteActivityRate(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteActivityRate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteActivityRate(arg0);
            return result;
        }
    }
    async deleteAddOnRate(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAddOnRate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAddOnRate(arg0);
            return result;
        }
    }
    async deleteBoatingRate(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBoatingRate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBoatingRate(arg0);
            return result;
        }
    }
    async deleteBooking(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBooking(arg0);
            return result;
        }
    }
    async deleteCredentialUser(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCredentialUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCredentialUser(arg0);
            return result;
        }
    }
    async deleteFoodRate(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFoodRate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFoodRate(arg0);
            return result;
        }
    }
    async deleteHotelRate(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteHotelRate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteHotelRate(arg0);
            return result;
        }
    }
    async deleteItineraryDay(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteItineraryDay(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteItineraryDay(arg0);
            return result;
        }
    }
    async deleteLead(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLead(arg0);
            return result;
        }
    }
    async deletePackage(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePackage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePackage(arg0);
            return result;
        }
    }
    async deletePromotion(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePromotion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePromotion(arg0);
            return result;
        }
    }
    async deleteRateOption(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRateOption(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRateOption(arg0, arg1);
            return result;
        }
    }
    async deleteReminder(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteReminder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteReminder(arg0);
            return result;
        }
    }
    async deleteReview(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteReview(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteReview(arg0);
            return result;
        }
    }
    async deleteTemplate(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTemplate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTemplate(arg0);
            return result;
        }
    }
    async deleteTravelRate(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTravelRate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTravelRate(arg0);
            return result;
        }
    }
    async deleteVendor(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteVendor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteVendor(arg0);
            return result;
        }
    }
    async getActivePromotions(): Promise<Array<Promotion>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivePromotions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivePromotions();
            return result;
        }
    }
    async getAllActivityRates(): Promise<Array<RateOption>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllActivityRates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllActivityRates();
            return result;
        }
    }
    async getAllAddOnRates(): Promise<Array<RateOption>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAddOnRates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAddOnRates();
            return result;
        }
    }
    async getAllBoatingRates(): Promise<Array<RateOption>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBoatingRates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBoatingRates();
            return result;
        }
    }
    async getAllFoodRates(): Promise<Array<RateOption>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFoodRates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFoodRates();
            return result;
        }
    }
    async getAllInvoices(): Promise<Array<Invoice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInvoices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInvoices();
            return result;
        }
    }
    async getAllPackages(): Promise<Array<Package>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPackages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPackages();
            return result;
        }
    }
    async getAllTravelRates(): Promise<Array<RateOption>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTravelRates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTravelRates();
            return result;
        }
    }
    async getAnalyticsSummary(): Promise<AnalyticsSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalyticsSummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalyticsSummary();
            return result;
        }
    }
    async getBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookings();
            return result;
        }
    }
    async getBookingsByPackage(arg0: bigint): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingsByPackage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingsByPackage(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCategories(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategories();
            return result;
        }
    }
    async getCompanySettings(): Promise<CompanySettings | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCompanySettings();
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCompanySettings();
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGuestRecords(): Promise<Array<GuestDetails>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGuestRecords();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGuestRecords();
            return result;
        }
    }
    async getHotelRates(): Promise<Array<HotelRate>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHotelRates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHotelRates();
            return result;
        }
    }
    async getInteractionLog(arg0: string): Promise<Array<InteractionLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInteractionLog(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInteractionLog(arg0);
            return result;
        }
    }
    async getInvoice(arg0: bigint): Promise<Invoice | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvoice(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvoice(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInvoicesByPackage(arg0: bigint): Promise<Array<Invoice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvoicesByPackage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvoicesByPackage(arg0);
            return result;
        }
    }
    async getItineraryByPackage(arg0: bigint): Promise<Array<ItineraryDay>> {
        if (this.processError) {
            try {
                const result = await this.actor.getItineraryByPackage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getItineraryByPackage(arg0);
            return result;
        }
    }
    async getLeadActivities(arg0: bigint): Promise<Array<LeadActivity>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeadActivities(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeadActivities(arg0);
            return result;
        }
    }
    async getLeadById(arg0: bigint): Promise<Lead | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeadById(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeadById(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeads(): Promise<Array<Lead>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeads();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeads();
            return result;
        }
    }
    async getLeadsByStage(): Promise<Array<StageCount>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeadsByStage();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeadsByStage();
            return result;
        }
    }
    async getPackages(): Promise<Array<Package>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPackages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPackages();
            return result;
        }
    }
    async getPromotions(): Promise<Array<Promotion>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPromotions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPromotions();
            return result;
        }
    }
    async getPublicPrivileges(arg0: bigint): Promise<UserPrivileges | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublicPrivileges(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublicPrivileges(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublishedReviews(): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublishedReviews();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublishedReviews();
            return result;
        }
    }
    async getReminders(): Promise<Array<Reminder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReminders();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReminders();
            return result;
        }
    }
    async getRemindersByEntity(arg0: bigint, arg1: string): Promise<Array<Reminder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRemindersByEntity(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRemindersByEntity(arg0, arg1);
            return result;
        }
    }
    async getReviews(): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReviews();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReviews();
            return result;
        }
    }
    async getTemplates(): Promise<Array<PackageTemplate>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTemplates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTemplates();
            return result;
        }
    }
    async getTemplatesByCategory(arg0: string): Promise<Array<PackageTemplate>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTemplatesByCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTemplatesByCategory(arg0);
            return result;
        }
    }
    async getTopDestinations(): Promise<Array<DestinationCount>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopDestinations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopDestinations();
            return result;
        }
    }
    async getUserPrivileges(arg0: bigint): Promise<UserPrivileges | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserPrivileges(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserPrivileges(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVendorById(arg0: bigint): Promise<Vendor | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVendorById(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVendorById(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVendors(): Promise<Array<Vendor>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVendors();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVendors();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listCredentialUsers(): Promise<Array<CredentialAccount>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCredentialUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCredentialUsers();
            return result;
        }
    }
    async loginWithCredentials(arg0: string, arg1: string): Promise<LoginResult> {
        if (this.processError) {
            try {
                const result = await this.actor.loginWithCredentials(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginWithCredentials(arg0, arg1);
            return result;
        }
    }
    async markInvoicePaid(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markInvoicePaid(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markInvoicePaid(arg0);
            return result;
        }
    }
    async markReminderDone(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markReminderDone(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markReminderDone(arg0);
            return result;
        }
    }
    async resetCredentialPassword(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetCredentialPassword(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetCredentialPassword(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveCompanySettings(arg0: CompanySettings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCompanySettings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCompanySettings(arg0);
            return result;
        }
    }
    async savePackage(arg0: Package): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.savePackage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.savePackage(arg0);
            return result;
        }
    }
    async setUserPrivileges(arg0: UserPrivileges): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setUserPrivileges(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUserPrivileges(arg0);
            return result;
        }
    }
    async updateBooking(arg0: Booking): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBooking(arg0);
            return result;
        }
    }
    async updateCredentialUser(arg0: bigint, arg1: string, arg2: string, arg3: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCredentialUser(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCredentialUser(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateHotelRate(arg0: string, arg1: string, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHotelRate(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHotelRate(arg0, arg1, arg2);
            return result;
        }
    }
    async updateInvoice(arg0: Invoice): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInvoice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInvoice(arg0);
            return result;
        }
    }
    async updateItineraryDay(arg0: ItineraryDay): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateItineraryDay(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateItineraryDay(arg0);
            return result;
        }
    }
    async updateLead(arg0: Lead): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLead(arg0);
            return result;
        }
    }
    async updateLeadStage(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLeadStage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLeadStage(arg0, arg1);
            return result;
        }
    }
    async updatePromotion(arg0: Promotion): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePromotion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePromotion(arg0);
            return result;
        }
    }
    async updateReminder(arg0: Reminder): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateReminder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateReminder(arg0);
            return result;
        }
    }
    async updateReview(arg0: Review): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateReview(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateReview(arg0);
            return result;
        }
    }
    async updateTemplate(arg0: PackageTemplate): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTemplate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTemplate(arg0);
            return result;
        }
    }
    async updateVendor(arg0: Vendor): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVendor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVendor(arg0);
            return result;
        }
    }
}
function from_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CompanySettings]): CompanySettings | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Invoice]): Invoice | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Lead]): Lead | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserPrivileges]): UserPrivileges | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Vendor]): Vendor | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
